# Generated by Django 5.0.7 on 2024-10-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_tumodelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tumodelo',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=255),
        ),
        migrations.AlterField(
            model_name='tumodelo',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
