# Generated by Django 5.0.7 on 2025-04-15 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_productotemporada_receta_delete_libro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productotemporada',
            old_name='meses_temporada',
            new_name='estación',
        ),
    ]
