# Generated by Django 5.0.7 on 2025-05-07 18:48

import django.db.models.deletion
import libreria.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_rename_meses_temporada_productotemporada_estación'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productotemporada',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productotemporada',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', validators=[libreria.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/', validators=[libreria.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='libreria.productotemporada'),
        ),
    ]
